included:
  - Example/GeoFeatures
  - Sources
  - Tests

excluded:
  - Scripts
  - Docs
  - bin

disabled_rules:
  - comma       # ToDo: Write custom comma rule that allows flexible_right_space
  - empty_count
  - todo
  - conditional_returns_on_newline
  - switch_case_on_newline
  - overridden_super_call
  - line_length
  - missing_docs # Development time only, remove when we get closer to production.  Also make this rule an error and not warning.

opt_in_rules:
  - closure_spacing
  - explicit_init
  - force_unwrapping
  - private_outlet
  - redundant_nil_coalesing

colon:
  flexible_right_spacing: true
  severity: error

cyclomatic_complexity:
  warning: 30
  error: 50

file_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 400
  error: 100

type_body_length:
  warning: 300
  error: 450

variable_name:
  min_length: # Note: it important that we allow variable names like x, y, z, m so our min length for error is 0
    warning: 0
    error: 0
  max_length:
    warning: 40
    error: 60

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
