included:
  - Example/GeoFeatures
  - Sources
  - Tests

excluded:
  - Scripts
  - Docs
  - bin

disabled_rules:
  - comma       # ToDo: Write custom comma rule that allows flexible_right_space
  - empty_count
  - todo
  - conditional_returns_on_newline
  - switch_case_on_newline
  - overridden_super_call
  - line_length
  - missing_docs # Development time only, remove when we get closer to production.  Also make this rule an error and not warning.

opt_in_rules:
  - closure_spacing
  - explicit_init
  - force_unwrapping
  - private_outlet
  - redundant_nil_coalescing

closing_brace:
  severity: error

closure_spacing:
  severity: error

colon:
  flexible_right_spacing: true
  severity: error

control_statement:
  severity: error

cyclomatic_complexity:
  warning: 30
  error: 50

file_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 400
  error: 100

function_parameter_count:
  warning: 5
  error: 8

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_nsgeometry_functions:
  severity: error

line_length:
  warning: 100
  error: 200

mark:
  severity: error

nesting:
  severity: error

opening_brace:
  severity: error

operator_whitespace:
  severity: error

private_outlet:
  severity: error

private_unit_test:
  severity:
    error: XCTestCase

redundant_nil_coalescing:
  severity: error

return_arrow_whitespace:
  severity: error

statement_position:
  severity: error

todo:
  severity: warning

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

trailing_whitespace:
  severity:
    warning:
      ignores_empty_lines: false
      ignores_comments: true

type_body_length:
  warning: 300
  error: 450

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 1000

valid_docs:
  severity: error

variable_name:
  min_length: # Note: it important that we allow variable names like x, y, z, m so our min length for error is 0
    warning: 0
    error: 0
  max_length:
    warning: 40
    error: 60

vertical_whitespace:
  severity: error

custom_rules:
  func_where_on_newline:
    included: ".*.swift"
    regex: "\)[ \t]*(?:->[ \t]*[a-zA-Z0-9]*[ \t]*)?[^\r\n][ \t]*where[ \t]"
    message: "func definitions must have their where clause on a new line."
    severity: error # violation severity. optional.

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
