codecov:
  notify:
    require_ci_to_pass: true
    
comment:
  behavior: default
  layout: header, diff, tree
  require_changes: false
  
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: true
    patch: true
    project: true
  ignore:
    - Example/*
    - Scripts/*
    - Docs/*
    - Tests/*
    - Pods/*
    - Applications/Xcode.app/*
    - vendor/*
    - Carthage/*
    - build/*
    - .build/*
    - .vagrant/*
    
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
